trigger:
- main 
- himanshu # Adjust to your branch name

pool:
  vmImage: 'ubuntu-latest'  # Use a suitable image for your environment


steps:
- script: |
    echo "Installing required packages..."
    sudo apt-get update
    sudo apt-get install -y python3 python3-pip
    pip3 install requests
  displayName: 'Install Python and Dependencies'

- script: |
    echo "Running the migration script..."
    python3 migration.py
    python3 changes.py
    python3 problem.py
    # python3 project.py
  displayName: 'Execute Migration Script'

###33


